from app.schemas.adicional import AdicionalCreate, AdicionalOut, AdicionalUpdate
from app.schemas.cliente import ClienteCreate, ClienteOut, ClienteUpdate
from app.schemas.comanda import (
    ComandaAbrirIn,
    ComandaCodigoCreate,
    ComandaCodigoOut,
    ComandaCodigoPatch,
    ComandaDeleteOut,
    ComandaItemCreate,
    ComandaItemMoveIn,
    ComandaItemOut,
    ComandaItemUpdate,
    ComandaListOut,
    ComandaOut,
    ComandaResetOut,
    ComandaStatusPatchIn,
    ItemAdicionalIn,
    ItemAdicionalOut,
    SugestaoProdutoOut,
)
from app.schemas.erp_config import ERPConfigOut, ERPConfigPatchIn
from app.schemas.common import PaginatedResponse
from app.schemas.pedido import (
    CupomHistoricoOut,
    ItemPedidoCreate,
    ItemPedidoOut,
    ItemPedidoUpdate,
    PedidoCreate,
    PedidoListOut,
    PedidoOut,
    PedidoStatusPatchIn,
)
from app.schemas.pagamento import (
    PagamentoCreate,
    PagamentoMaquininhaConfirmar,
    PagamentoMaquininhaIniciar,
    PagamentoOut,
    ResumoPagamentoOut,
)
from app.schemas.produto import EstoquePatchIn, ProdutoCreate, ProdutoOut, ProdutoUpdate
from app.schemas.relatorio import (
    FaturamentoDiaOut,
    FaturamentoPeriodoOut,
    FechamentoCaixaOut,
    ResumoDiaOut,
    TopProdutoOut,
)

__all__ = [
    "PaginatedResponse",
    "AdicionalCreate",
    "AdicionalOut",
    "AdicionalUpdate",
    "ComandaCodigoCreate",
    "ComandaCodigoPatch",
    "ComandaCodigoOut",
    "ComandaDeleteOut",
    "ComandaAbrirIn",
    "ComandaItemCreate",
    "ComandaItemMoveIn",
    "ComandaItemUpdate",
    "ComandaItemOut",
    "ItemAdicionalIn",
    "ItemAdicionalOut",
    "ComandaListOut",
    "ComandaOut",
    "ComandaResetOut",
    "ComandaStatusPatchIn",
    "SugestaoProdutoOut",
    "ERPConfigOut",
    "ERPConfigPatchIn",
    "PagamentoCreate",
    "PagamentoMaquininhaIniciar",
    "PagamentoMaquininhaConfirmar",
    "PagamentoOut",
    "ResumoPagamentoOut",
    "ClienteCreate",
    "ClienteOut",
    "ClienteUpdate",
    "ProdutoCreate",
    "ProdutoOut",
    "ProdutoUpdate",
    "EstoquePatchIn",
    "PedidoCreate",
    "PedidoOut",
    "PedidoListOut",
    "CupomHistoricoOut",
    "PedidoStatusPatchIn",
    "ItemPedidoCreate",
    "ItemPedidoOut",
    "ItemPedidoUpdate",
    "ResumoDiaOut",
    "FechamentoCaixaOut",
    "TopProdutoOut",
    "FaturamentoDiaOut",
    "FaturamentoPeriodoOut",
]
